minor fixes

diff --git a/Dockerfile.apache b/Dockerfile.apache
--- a/Dockerfile.apache
+++ b/Dockerfile.apache
@@ -9,7 +9,6 @@ RUN apt-get update && apt-get -y upgrade \
         git \
         unzip \
         apache2 \
-        mysql-server \
         php8.1 \
         libapache2-mod-php8.1 \
         php8.1-common \
@@ -24,8 +23,26 @@ RUN apt-get update && apt-get -y upgrade \
     elif gpg --version | grep -q '^gpg (GnuPG) 1\.'; then \
         apt-get install -y --no-install-recommends gnupg-curl; \
     fi \
-    && a2enmod rewrite headers
+    && a2enmod rewrite headers \
+    && wget -O /usr/local/bin/composer.php "https://getcomposer.org/installer"; \
+    actualSig="$(wget -q -O - https://composer.github.io/installer.sig)"; \
+    currentSig="$(shasum -a 384 /usr/local/bin/composer.php | awk '{print $1}')"; \
+    if [ "$currentSig" != "$actualSig" ]; then \
+        echo "Warning: Failed to verify composer signature."; \
+        exit 1; \
+	fi; \
+    # Install composer
+    php /usr/local/bin/composer.php --quiet --filename=/usr/local/bin/composer \
+    && chmod +x /usr/local/bin/composer; 
 
-EXPOSE 80
+
+    WORKDIR /var/www/html
+    COPY uvdesk/ .
+    ENV COMPOSER_ALLOW_SUPERUSER=1
+
+    # COPY uvdesk/composer.json uvdesk/composer.lock ./
+    RUN composer install --optimize-autoloader
+
+EXPOSE 8081
 
 CMD ["apache2ctl", "-D", "FOREGROUND"]
